services:
    ToolboxBundle\Document\Areabrick\Columns\Columns:
        parent: ToolboxBundle\Document\Areabrick\AbstractAreabrick
        autowire: true
        tags:
            - { name: pimcore.area.brick, id: columns }
toolbox:
    areas:
        columns:
            config_parameter:
                reload_on_close: true
            config_elements:
                type:
                    type: select
                    title: 'Columns'
                    config:
                        store:
                            column_12: '1 Column'
                            column_4_8: '2 Columns (33:66)'
                            column_8_4: '2 Columns (66:33)'
                            column_3_9: '2 Columns (25:75)'
                            column_9_3: '2 Columns (75:25)'
                            column_6_6: '2 Columns (50:50)'
                            column_4_4_4: '3 Columns (33:33:33)'
                        default: column_6_6
                equal_height:
                    type: checkbox
                    title: 'Equal heights?'
                    config: ~
                additional_classes:
                    type: additionalClasses
                    config:
                        store: ~