services:
    ToolboxBundle\Document\Areabrick\Container\Container:
        parent: ToolboxBundle\Document\Areabrick\AbstractAreabrick
        tags:
            - { name: pimcore.area.brick, id: container }
toolbox:
    areas:
        container:
            config_elements:
                full_width_container:
                    type: checkbox
                    title: 'Fluid Container (Full Width)'
                    config: ~
                additional_classes:
                    type: additionalClasses
                    config:
                        store: ~