services:
    ToolboxBundle\Document\Areabrick\LinkList\LinkList:
        parent: ToolboxBundle\Document\Areabrick\AbstractAreabrick
        tags:
            - { name: pimcore.area.brick, id: linkList }
toolbox:
    areas:
        linkList:
            config_elements:
                additional_classes:
                    type: additionalClasses
                    config:
                        store: ~