services:
    ToolboxBundle\Document\Areabrick\Separator\Separator:
        parent: ToolboxBundle\Document\Areabrick\AbstractAreabrick
        tags:
            - { name: pimcore.area.brick, id: separator }
toolbox:
    areas:
        separator:
            config_elements:
                space:
                    type: select
                    title: 'Space before & after separator'
                    config:
                        store:
                            default: 'Default'
                            medium: 'Medium'
                            large: 'Large'
                        default: default
                additional_classes:
                    type: additionalClasses
                    config:
                        store: ~