services:
    ToolboxBundle\Document\Areabrick\Teaser\Teaser:
        parent: ToolboxBundle\Document\Areabrick\AbstractAreabrick
        tags:
            - { name: pimcore.area.brick, id: teaser }
toolbox:
    areas:
        teaser:
            config_elements:
                type:
                    type: select
                    title: 'Type'
                    config:
                        name: type
                        store:
                            direct: 'Direct'
                            snippet: 'Snippet'
                        default: direct
                layout:
                    type: select
                    title: 'Layout'
                    conditions:
                        - type: direct
                    config:
                        store:
                            default: 'Default'
                        default: default
                use_light_box:
                    type: checkbox
                    title: 'use Lightbox?'
                    config: ~
                additional_classes:
                    type: additionalClasses
                    config:
                        store: ~
